name: Deploy to EC2

on:
  push:
    branches:
      - master  # Deploy when pushing to the 'master' branch (modify as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}
    
    - name: Set up SSH Key
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy to EC2
      run: |
        ssh -t -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd test-app/django-mogo-test-app
          git pull origin master
          source ../../env/bin/activate
          fuser -k 8000/tcp
          gunicorn --bind 0.0.0.0:8000 mongo_project.wsgi:application
        EOF
