name: Deploy to EC2

on:
  push:
    branches:
      - master  # Deploy when pushing to the 'master' branch (modify as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -i "${{ secrets.EC2_PRIVATE_KEY }}" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}
          cd djangomongo-app/django-mogo-test-app/
          git pull origin master
          conda activate env  # Activate the virtual environment if using one
          pip install -r requirements.txt  # Install new dependencies
          fuser -k 8000/tcp  # Kill the server
          python manage.py runserver  0:8000 # Restart the server
        EOF
