name: Deploy to EC2

on:
  push:
    branches:
      - master  # Deploy when pushing to the 'main' branch (modify as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd 
          git pull origin master
          source venv/bin/activate  # Activate the virtual environment if using one
          pip install -r requirements.txt  # Install new dependencies
          python manage.py runserver  0:8000# Restart the server
        EOF
